### PR TITLE
[API] fix validate and evaluation api config, set_trial_config #984

### PR DESCRIPTION
**Pull request by hongsw**
- **feat: refactor SQL Trial DB from Pandas Trial DB, and Test code**
- **🚑 fix: Set correct WORK_DIR based on environment variable**

### CODE REVIEW

**Comment by hongsw** [comment]
api git:(Feature/api/984) ✗ python -m pytest tests/test_trial_config.py  # 테스트 실행 =============================================================================================== test session starts =============================================================================================== platform darwin -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0 rootdir: /Users/martin/Development/org_autorag/AutoRAG/api plugins: anyio-4.6.2.post1 collected 7 items                                                                                                                                                                                                   tests/test_trial_config.py .......                                                                                                                                                                          [100%]  ================================================================================================ warnings summary ================================================================================================= ../.venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:291 ../.venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:291   /Users/martin/Development/org_autorag/AutoRAG/.venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/     warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)  -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ========================================================================================== 7 passed, 2 warnings in 0.63s

**Comment by hongsw** [comment]
```

AUTORAG_API_ENV: dev
--------------------------------
### Server start
--------------------------------
collected 6 items                                                                                                                                                                                  

tests/test_app.py::test_create_project PASSED
tests/test_app.py::test_create_trial FAILED
tests/test_app.py::test_create_trial_invalid_project PASSED
tests/test_app.py::test_get_trial PASSED
tests/test_app.py::test_delete_trial PASSED
tests/test_app.py::test_environment_variables PASSED
```

**Comment by hongsw** [comment]
Test http://localhost:5555/

**Comment by hongsw** [comment]
```
python -m pytest tests/test_project_db.py -s -v
====================================================================== test session starts ======================================================================
platform darwin -- Python 3.11.10, pytest-8.3.3, pluggy-1.5.0 -- /Users/martin/Development/org_autorag/AutoRAG/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/martin/Development/org_autorag/AutoRAG/api
configfile: pytest.ini
plugins: asyncio-0.24.0, anyio-4.6.2.post1
asyncio: mode=Mode.AUTO, default_loop_scope=function
collected 8 items                                                                                                                                               

tests/test_project_db.py::test_db_initialization 
[테스트] DB 초기화
- DB 파일 생성 확인: /var/folders/v0/_g3z68kd417dkyyj406b1tpc0000gn/T/tmpj604z2tw/test_project/project.db
PASSED
tests/test_project_db.py::test_set_and_get_trial 
[테스트] Trial 저장 및 조회
- Trial 저장: ID=test_trial_1
- Trial 조회 및 데이터 검증

[Config 검증]
원본 Config: {'trial_id': 'test_trial_1', 'project_id': 'test_project', 'raw_path': '/path/to/raw', 'corpus_path': '/path/to/corpus', 'qa_path': '/path/to/qa', 'config_path': '/path/to/config', 'metadata': {}}
조회된 Config: {'trial_id': 'test_trial_1', 'project_id': 'test_project', 'raw_path': '/path/to/raw', 'corpus_path': '/path/to/corpus', 'qa_path': '/path/to/qa', 'config_path': '/path/to/config', 'metadata': {}}
- 검증 완료: 모든 필드가 일치함
PASSED
tests/test_project_db.py::test_get_nonexistent_trial 
[테스트] 존재하지 않는 Trial 조회
- 존재하지 않는 ID로 조회: nonexistent_id
- 검증 완료: None 반환 확인
PASSED
tests/test_project_db.py::test_set_trial_config 
[테스트] Trial 설정 업데이트
- 기존 Trial 저장: ID=test_trial_1
- 새로운 설정으로 업데이트
- 검증 완료: 설정 업데이트 확인
PASSED
tests/test_project_db.py::test_get_trials_by_project 
[테스트] 프로젝트별 Trial 목록 조회
- 첫 번째 Trial 저장
- 두 번째 Trial 생성 및 저장
- 페이지네이션 테스트 (limit=1)
- 전체 Trial 조회 테스트
- 검증 완료: 총 2개의 Trial 확인
PASSED
tests/test_project_db.py::test_get_all_config_ids PASSED
tests/test_project_db.py::test_delete_trial PASSED
tests/test_project_db.py::test_get_all_trial_ids PASSED

======================================================================= 8 passed in 0.22s =
```

**Comment by hongsw** [comment]
- [ ] "Move config folder data to SQLite trial schema"

**Comment by hongsw** [comment]
image

**Review by vkehfdl1 — APPROVED** [review]
Let's merge this first and split the issues

**Pull request merged**
