### PR TITLE
Add running web interface in Runner with Gradio

### LINKED ISSUE #616: How can I add custom embedding model when running web
I have custom huggingface embedding model in my pipeline.yaml.  
When running as api server, I can add my custom model like below
```python
autorag.embedding_models["custom model"] = LazyInit(
    HuggingFaceEmbedding, model_name="custom_model"
)
runner = Runner.from_yaml("./6/pipeline.yaml")
runner.run_api_server()
```
But run_web support cli only, so I can't add custom model like above.  
How can I add custom model?
Is there any reason why `run_web` is not supported by the Python SDK, like `run_api_server()`?

### PR DESCRIPTION
**Pull request by rjwharry**
close #616 

There are limitations to running the web interface with Streamlit when using custom models (embedding, llm).  
Here's what I did to resolve this issue.
1. Use Gradio
This PR uses Gradio as the web interface because it can be run in the same process that defined the custom model.
1. Fix error of get_event_loop
When running web with Gradio, I faced an error in loop = asyncio.get_event_loop() in the autorag module. Here is the detailed error log.
```bash
loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/anaconda3/envs/autorag/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'AnyIO worker thread'.
```
I've modified it to create a new event loop when there is no running one, since it presumably doesn't have a running one, and the [official asyncio documentation recommends](https://docs.python.org/3/library/asyncio-eventloop.html) using get_running_event_loop() rather than get_event_loop().  
Also, we didn't use `asyncio.run()` because it tends to be used in entry points.

### CODE REVIEW

**Comment by vkehfdl1** [comment]
@rjwharry When you are ready to review, please assign me as reviewer.
Plus, if there is something to help needed, please mention me.

**Comment by rjwharry** [comment]
@vkehfdl1 
I don't know why, but I can't assign you as a reviewer, so I mentioned it in this comment

**Comment by vkehfdl1** [comment]
@rjwharry 
I fixed several codes that used `asyncio.run` directly to prevent duplicated event loop in one thread.
I am trying to make a test code for this feature. Any idea?

Meanwhile, please add documentation. You need to edit`docs/source/deploy/web.md`

**Comment by rjwharry** [comment]
> @rjwharry I fixed several codes that used `asyncio.run` directly to prevent duplicated event loop in one thread. I am trying to make a test code for this feature. Any idea?
> 
> Meanwhile, please add documentation. You need to edit`docs/source/deploy/web.md`

@vkehfdl1 Thanks for pointing out what I missed.  
I'll have to think about how to create test code for this feature and will share it as soon as I come up with something.  
  
Also, I missed working on the documentation too. Thanks for letting me know.

**Comment by rjwharry** [comment]
I'm trying several ways to test this feature, but all failed. Can you share me ideas?
1. Just write test code
```python
def test_web_library():
    runner = Runner.from_yaml(os.path.join(resource_dir, "result_project", "best.yaml"))
    runner.run_web()
```
Here is the error log.
```bash
OSError: Cannot find empty port in range: 7680-7680.
```
2. Set server_port as free port. But I got same error
```python
@pytest.fixture
def server_port(unused_tcp_port):
    return unused_tcp_port

def test_web_library(server_port):
    runner = Runner.from_yaml(os.path.join(resource_dir, "result_project", "best.yaml"))
    runner.run_web(server_port=server_port)
```
Here is the error log
```bash
OSError: Cannot find empty port in range: 42877-42877.
```
3. Try to find free port another way
```python
@pytest.fixture
def server_port():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("", 0))
        return s.getsockname()[1]

def test_web_library(server_port):
    runner = Runner.from_yaml(os.path.join(resource_dir, "result_project", "best.yaml"))
    runner.run_web(server_port=server_port)
```
Here is the error log
```bash
OSError: Cannot find empty port in range: 34159-34159.
```
4. Add asyncio. Got same error
`RuntimeError: There is no current event loop in thread 'Thread-4 (run)'.` error occurred at the same time. I also tried to add an asynchronous event loop, which also failed with the same error.
```python
@pytest.fixture(scope="module")
def event_loop():
    loop = get_event_loop()
    yield
    loop.close()

def test_web_library(server_port):
    runner = Runner.from_yaml(os.path.join(resource_dir, "result_project", "best.yaml"))
    runner.run_web(server_port=server_port)
```

The same error occurred on all trials, here is the full log
```bash
tests/autorag/test_web.py::test_web_library
  ~/anaconda3/envs/llm-study/lib/python3.11/site-packages/_pytest/threadexception.py:77: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-4 (run)
  
  Traceback (most recent call last):
    File "~/anaconda3/envs/llm-study/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
      self.run()
    File "~/anaconda3/envs/llm-study/lib/python3.11/threading.py", line 982, in run
      self._target(*self._args, **self._kwargs)
    File "~/anaconda3/envs/llm-study/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
      return asyncio.run(self.serve(sockets=sockets))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/anaconda3/envs/llm-study/lib/python3.11/site-packages/nest_asyncio.py", line 26, in run
      loop = asyncio.get_event_loop()
             ^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/anaconda3/envs/llm-study/lib/python3.11/site-packages/nest_asyncio.py", line 40, in _get_event_loop
      loop = events.get_event_loop_policy().get_event_loop()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "~/anaconda3/envs/llm-study/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
      raise RuntimeError('There is no current event loop in thread %r.'
  RuntimeError: There is no current event loop in thread 'Thread-4 (run)'.
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/autorag/test_web.py::test_web_library
  ~/anaconda3/envs/llm-study/lib/python3.11/site-packages/_pytest/threadexception.py:57: RuntimeWarning: coroutine 'Server.serve' was never awaited
    del self.args
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================================= short test summary info ==============================================================================================================
FAILED tests/autorag/test_web.py::test_web_library - OSError: Cannot find empty port in range: 53031-53031. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
```

**Comment by vkehfdl1** [comment]
@rjwharry Yes I am investigating same error also. 
At one thread there has to be one event loop right? But it looks like gradio and AutoRAG tries to use different event loop.
I tried to use different thread between at running gradio. But it didn't work well (get another error)
I'm looking for how to fix it

**Comment by vkehfdl1** [comment]
@rjwharry Anyway thanks for the documentation

**Comment by rjwharry** [comment]
As you said, event loop is the problem.  
For the test, I modified `asyncio.run` in `uvicorn` to our safe `get_event_loop()`, it works.  
```python
def run(self, sockets: list[socket.socket] | None = None) -> None:
        self.config.setup_event_loop()
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
        # return asyncio.run(self.serve(sockets=sockets))
        return loop.run_until_complete(self.serve(sockets=sockets))
```
I'll figure it out how to solve this without changing `uvicorn`

**Comment by rjwharry** [comment]
I checked that the error was occurring in `nest_asyncio` and not `gradio`. When I ran it as a `python` command, nest_asyncio was not used, but only in `pytest`. I checked the `conftest.py` file and nest_asyncio was being used in the pytest session. I removed it and gradio worked fine. Please check if it is okay to remove nest_asyncio from pytest. When I tested the autorag node locally, it tested fine.

**Comment by vkehfdl1** [comment]
```
=============================== short test summary info ===============================
FAILED tests/autorag/test_deploy.py::test_runner_api_server - RuntimeError: This event loop is already running
========= 1 failed, 250 passed, 8 skipped, 172 warnings in 498.21s (0:08:18) ==========
```
I have an error at `test_runner_api_server` after I deleted `nest_asyncio.apply()`.
So I have to fix api server problem either.

**Comment by rjwharry** [comment]
I think this error is caused by FastAPI. FastAPI have already run event loop, so we need nest_asyncio when run api server.  
We already did it in `run_api_server` in `deploy.py` for this reason. But in `test_deploy.py`, we run FastAPI directly by TestClient not `run_api_server`.   
So I think we need to add `nest_asyncio` in `test_runner_api_server` function and it works on my local

**Review by vkehfdl1 — APPROVED** [review]
LGTM

**Pull request merged**
