### PR TITLE
Add HotpotQA Dataset Adapted for AutoRAG Format

### PR DESCRIPTION
**Pull request by gnekt**
This pull request introduces the HotpotQA dataset, adapted to fit the requirements for AutoRAG. The modifications ensure compatibility with AutoRAG's input specifications.

**What I did to HotPotQA** (ref. [gnekt/hotpotqa_sample_autorag)](https://huggingface.co/datasets/gnekt/hotpotqa_sample_autorag/viewer/qa)

- _Data Preprocessing_: Implemented preprocessing scripts to automate the conversion process, ensuring data integrity and format consistency.
- Dataset Adaptation: Converted the original HotpotQA format to align with the AutoRAG data structure.

Please review the changes and provide any feedback or approval to merge this addition into the main branch.
I will add also qa_train but it requires much more time to process.

### CODE REVIEW

**Review by vkehfdl1 — CHANGES_REQUESTED** [review]
Hello @gnekt 
First, thanks to your contribution. It is really great that we have new contributor!

But, there are some minor change have to be done at the dataset. 
Hotpot QA is **multi-hop** question dataset, which needs more than two passages to properly answer the question. 
But, in your QA dataset, the retrieval_gt looks like this.

```
[ "Scott Derrickson_0", "Ed Wood_0" ]
```

In AutoRAG, when you put this 1-d list, it will convert to 2-d list like below.

```
[[ "Scott Derrickson_0", "Ed Wood_0" ]]
```
It does not mean it is multi-hop. The retrieval system will mark that "Scott Derrickson_0" or "Ed Wood_0" will be the retrieval gt.

So you have to modify the retrieval gt like this.

```
[ ["Scott Derrickson_0"], ["Ed Wood_0" ]]
```

Second, the generation_gt columns must be a list. Since it has only one ground truth answer in the dataset, just make it to list.

The other things looks great to me. 
Please modify your dataset and re-review to me.

Thanks again :)

**Comment by vkehfdl1** [comment]
Plus, you might be careful to run this whole dataset using paid model. (paid embedding or paid LLM)
The 1.98M corpus and 7.4K questions looks extremely **huge** for AutoRAG and might need very expensive calculations. 

It can be great you add warning signs that run whole dataset at once to AutoRAG will be extremely expensive.

**Comment by gnekt** [comment]
> Hello @gnekt First, thanks to your contribution. It is really great that we have new contributor!
> 
> But, there are some minor change have to be done at the dataset. Hotpot QA is **multi-hop** question dataset, which needs more than two passages to properly answer the question. But, in your QA dataset, the retrieval_gt looks like this.
> 
> ```
> [ "Scott Derrickson_0", "Ed Wood_0" ]
> ```
> 
> In AutoRAG, when you put this 1-d list, it will convert to 2-d list like below.
> 
> ```
> [[ "Scott Derrickson_0", "Ed Wood_0" ]]
> ```
> 
> It does not mean it is multi-hop. The retrieval system will mark that "Scott Derrickson_0" or "Ed Wood_0" will be the retrieval gt.
> 
> So you have to modify the retrieval gt like this.
> 
> ```
> [ ["Scott Derrickson_0"], ["Ed Wood_0" ]]
> ```
> 
> Second, the generation_gt columns must be a list. Since it has only one ground truth answer in the dataset, just make it to list.
> 
> The other things looks great to me. Please modify your dataset and re-review to me.
> 
> Thanks again :)

Fixed.


> Plus, you might be careful to run this whole dataset using paid model. (paid embedding or paid LLM) The 1.98M corpus and 7.4K questions looks extremely **huge** for AutoRAG and might need very expensive calculations.
> 
> It can be great you add warning signs that run whole dataset at once to AutoRAG will be extremely expensive.

Added a Disclaimer on the HuggingFace Repo. 
Should i put it also onto other pages?

**Comment by vkehfdl1** [comment]
@gnekt  Thanks!
Can you add disclaimer at the load_hotpotqa_dataset.py as annotation?

**Comment by gnekt** [comment]
I've done a compact version of hotpotqa, the loader now reflects that change.

Basically i sampled 500 question from the original question set, then aligned with the needed corpus (~1100 docs) + some documents augmentation (~5000 docs)

**Pull request merged**
