### PR TITLE
Feat/dashboard

### PR DESCRIPTION
**Pull request by hongsw**
image

```
$ autorag dashboard

```

### CODE REVIEW

**Comment by hongsw** [comment]
# AutoRAG Dashboard Features

AutoRAG Dashboard is designed to streamline and enhance your RAG test summary data analysis workflow. Here are the key features that make it a powerful tool for researchers and analysts:

### Set Project Path
Easily set the path for your project directory where all files related to your current project are stored. This simplifies file management and ensures that all project-related data is organized and accessible.

### Select Test Number
Choose a specific test number to focus on analyzing. This feature allows users to filter results and operations by test, making it easy to navigate through complex datasets or to compare different tests.

### Config Markdown View
Config Markdown View
Configure views in Markdown to generate reports or notes that include both analytical insights and visual data. This feature enables you to output your analysis in a widely-supported format for easy sharing and reviewing.

### Scatter Plot View
Scatter Plot View
Visualize data with a scatter plot to identify trends, correlations, and outliers effectively. This graphical representation helps in making data-driven decisions and enhances the ability to convey complex data simply.

**Comment by vkehfdl1** [comment]
@hongsw I am making this branch to draft because it needs to integrate to the autorag library well. Works in the any trial directory that user given. I will work on this in your branch, and possibly add more features to the dashboard. Huge thanks :)

**Comment by vkehfdl1** [comment]
Screenshot 2024-05-20 at 12 21 12 PM
Screenshot 2024-05-20 at 12 21 07 PM
Screenshot 2024-05-20 at 11 58 10 AM

**Review by bwook00 — APPROVED** [review]
What a nice dashboard!!
huge thanks to @hongsw 👍

**Comment by vkehfdl1** [comment]
I'll bypass the unit test since it passed on my local test (missing openai api key..)

**Pull request merged**
