### PR TITLE
✨ feat: Update supporting nodes and modules information in index.md

### PR DESCRIPTION
**Pull request by hongsw**
This commit updates the list of supporting nodes and modules in the index.md file, providing a structured table layout for better clarity and organization. Additionally, it includes instructions to access a more comprehensive and up-to-date list on the dedicated Notion page.

### CODE REVIEW

**Review by vkehfdl1 — CHANGES_REQUESTED** [review]
image

The result looks like this.

Can you add outline at the table? Because it is hard to recognize.

**Comment by hongsw** [comment]
image
image

**Comment by hongsw** [comment]
```ERROR tests/autorag/nodes/passagefilter/test_percentile_cutoff.py
====== 325 passed, 70 skipped, 180 warnings, 1 error in 123.36s (0:02:03) ======```
1 failing details. I don't know, I just changed `md` file. Help me @vkehfdl1 , @bwook00

**Comment by vkehfdl1** [comment]
@hongsw bwook fixed this!!!

**Review by vkehfdl1 — APPROVED** [review]
LGTM

**Pull request merged**
