### PR TITLE
🚑 fix: Update requirements for Google Colab compatibility

### PR DESCRIPTION
**Pull request by hongsw**
Fixed module versions:
```
× Cannot uninstall blinker 1.4

× google-colab 1.0.0 requires ipykernel==5.5.6, but you have ipykernel 6.29.5 which is incompatible.

```

### CODE REVIEW

**Comment by hongsw** [comment]
Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.5/111.5 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 977.7/977.7 kB 17.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 92.1 MB/s eta 0:00:00
  Building wheel for blinker (setup.py) ... done
  Building wheel for ipywidgets-bokeh (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 3.0.3 requires blinker>=1.6.2, but you have blinker 1.4 which is incompatible.
holoviews 1.19.1 requires bokeh>=3.1, but you have bokeh 2.4.3 which is incompatible.
holoviews 1.19.1 requires panel>=1.0, but you have panel 0.14.4 which is incompatible.

**Comment by hongsw** [comment]
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.5/111.5 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 977.7/977.7 kB 17.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.0/121.0 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.8/20.8 MB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 92.1 MB/s eta 0:00:00
  Building wheel for blinker (setup.py) ... done
  Building wheel for ipywidgets-bokeh (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 3.0.3 requires blinker>=1.6.2, but you have blinker 1.4 which is incompatible.
holoviews 1.19.1 requires bokeh>=3.1, but you have bokeh 2.4.3 which is incompatible.
holoviews 1.19.1 requires panel>=1.0, but you have panel 0.14.4 which is incompatible.
```

**Comment by hongsw** [comment]
image

**Comment by hongsw** [comment]
testing...

**Comment by vkehfdl1** [comment]
```
%%shell
apt-get remove python3-blinker
pip install blinker==1.8.2
pip install -Uq ipykernel==5.5.6 ipywidgets-bokeh==1.0.2
```

Use this at colab to install

**Pull request closed without merging**
